# THIS IS ONLY EXAMPLE, THAT PRODUCTION ENV (PROFILE) WOULD BE SEPARATED FROM DEV IN REAL-WORLD SCENARIO.
# CONFIG PARAMS WOULD BE PICKED FROM THE PIPELINE.
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: ${PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    org.springframework: WARN
